/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AccessTokens } from './models/AccessTokens';
export type { Addr } from './models/Addr';
export type { AppPermissionDao } from './models/AppPermissionDao';
export type { AuthToken } from './models/AuthToken';
export type { AuthTokenDao } from './models/AuthTokenDao';
export type { CertDnsRenewReq } from './models/CertDnsRenewReq';
export type { CertificateData } from './models/CertificateData';
export type { CreateAppPermissionRequest } from './models/CreateAppPermissionRequest';
export type { CreateAppPermissionResult } from './models/CreateAppPermissionResult';
export type { CreateExternalApplicationRequest } from './models/CreateExternalApplicationRequest';
export type { CreateHostServerRequest } from './models/CreateHostServerRequest';
export type { CreateHostServerTypeBodyRequest } from './models/CreateHostServerTypeBodyRequest';
export type { CreateHostServerTypeMappingRequest } from './models/CreateHostServerTypeMappingRequest';
export type { CreateInfraDependencyRequest } from './models/CreateInfraDependencyRequest';
export type { CreateNewUserRequest } from './models/CreateNewUserRequest';
export type { CreatePlatformTypeBodyRequest } from './models/CreatePlatformTypeBodyRequest';
export type { CreatePlatformTypeMappingRequest } from './models/CreatePlatformTypeMappingRequest';
export type { CreateRolePermissionMappingRequest } from './models/CreateRolePermissionMappingRequest';
export type { CreateRolePermissionMappingResponse } from './models/CreateRolePermissionMappingResponse';
export type { CreateSecretRequest } from './models/CreateSecretRequest';
export type { CreateSshKeyHostMappingRequest } from './models/CreateSshKeyHostMappingRequest';
export type { CreateSshKeyHostMappingRequestWithoutUserID } from './models/CreateSshKeyHostMappingRequestWithoutUserID';
export type { CreateSshKeyHostMappingResponse } from './models/CreateSshKeyHostMappingResponse';
export type { CreateSshKeyRequest } from './models/CreateSshKeyRequest';
export type { CreateSshKeyResponse } from './models/CreateSshKeyResponse';
export type { CreateUserApplicationRequest } from './models/CreateUserApplicationRequest';
export type { CreateUserRoleRequest } from './models/CreateUserRoleRequest';
export type { CreateUserRoleResponse } from './models/CreateUserRoleResponse';
export type { DeleteRolePermissionMappingRequest } from './models/DeleteRolePermissionMappingRequest';
export type { DeleteRolePermissionMappingResponse } from './models/DeleteRolePermissionMappingResponse';
export type { DeleteSshKeyHostMappingResponse } from './models/DeleteSshKeyHostMappingResponse';
export type { DisableUserRequest } from './models/DisableUserRequest';
export type { Duration } from './models/Duration';
export type { EnableDisableUserResponse } from './models/EnableDisableUserResponse';
export type { EnableUserRequest } from './models/EnableUserRequest';
export type { ExternalApplicationDao } from './models/ExternalApplicationDao';
export type { ExternalApplicationInfo } from './models/ExternalApplicationInfo';
export type { ExternalAppSecretMetadata } from './models/ExternalAppSecretMetadata';
export type { GarageNodeRequest } from './models/GarageNodeRequest';
export type { GarageNodeResult } from './models/GarageNodeResult';
export type { GarageTokenRequest } from './models/GarageTokenRequest';
export type { GarageTokenResult } from './models/GarageTokenResult';
export type { GetAllAppPermissionsResponse } from './models/GetAllAppPermissionsResponse';
export type { GetAllRolesResponse } from './models/GetAllRolesResponse';
export type { GetRolePermissionMappingsResponse } from './models/GetRolePermissionMappingsResponse';
export type { GetRolesPermissionCountResponse } from './models/GetRolesPermissionCountResponse';
export type { GetUserByIdResponse } from './models/GetUserByIdResponse';
export type { HostedDbPlatform } from './models/HostedDbPlatform';
export type { HostServer } from './models/HostServer';
export type { HostServerIDResponse } from './models/HostServerIDResponse';
export type { HostServerResponse } from './models/HostServerResponse';
export type { HostServersResponse } from './models/HostServersResponse';
export type { HostServerType } from './models/HostServerType';
export type { InfraDependencyDao } from './models/InfraDependencyDao';
export type { JsonInt } from './models/JsonInt';
export type { LoginResponseInfo } from './models/LoginResponseInfo';
export type { MariaDBInstallRequest } from './models/MariaDBInstallRequest';
export type { MariaDBInstallResult } from './models/MariaDBInstallResult';
export type { NetworkProbeResponse } from './models/NetworkProbeResponse';
export type { PingHostServerRequest } from './models/PingHostServerRequest';
export type { PingRequest } from './models/PingRequest';
export type { PingResponse } from './models/PingResponse';
export type { PlatformType } from './models/PlatformType';
export type { PostgresAppSetupRequest } from './models/PostgresAppSetupRequest';
export type { PostgresAppSetupResult } from './models/PostgresAppSetupResult';
export type { ProbeByHostIdRequest } from './models/ProbeByHostIdRequest';
export type { ProbeByHostnameRequest } from './models/ProbeByHostnameRequest';
export type { ProxmoxAPITokenCreateRequest } from './models/ProxmoxAPITokenCreateRequest';
export type { ProxmoxAPITokenCreateResult } from './models/ProxmoxAPITokenCreateResult';
export type { ProxmoxAuthOptions } from './models/ProxmoxAuthOptions';
export type { ProxmoxContainer } from './models/ProxmoxContainer';
export type { ProxmoxContainerListResult } from './models/ProxmoxContainerListResult';
export type { ProxmoxGuestIPAddress } from './models/ProxmoxGuestIPAddress';
export type { ProxmoxGuestNetworkInterface } from './models/ProxmoxGuestNetworkInterface';
export type { ProxmoxGuestSummaryResult } from './models/ProxmoxGuestSummaryResult';
export type { ProxmoxLXCRequest } from './models/ProxmoxLXCRequest';
export type { ProxmoxLXCResourcesResult } from './models/ProxmoxLXCResourcesResult';
export type { ProxmoxLXCResourcesUpdateRequest } from './models/ProxmoxLXCResourcesUpdateRequest';
export type { ProxmoxLXCResult } from './models/ProxmoxLXCResult';
export type { ProxmoxNodeBridge } from './models/ProxmoxNodeBridge';
export type { ProxmoxNodeOptionsResult } from './models/ProxmoxNodeOptionsResult';
export type { ProxmoxNodeStorage } from './models/ProxmoxNodeStorage';
export type { ProxmoxPVEUserCreateRequest } from './models/ProxmoxPVEUserCreateRequest';
export type { ProxmoxPVEUserCreateResult } from './models/ProxmoxPVEUserCreateResult';
export type { ProxmoxStorageContent } from './models/ProxmoxStorageContent';
export type { ProxmoxVM } from './models/ProxmoxVM';
export type { ProxmoxVMCreateRequest } from './models/ProxmoxVMCreateRequest';
export type { ProxmoxVMCreateResult } from './models/ProxmoxVMCreateResult';
export type { ProxmoxVMHardwareActionRequest } from './models/ProxmoxVMHardwareActionRequest';
export type { ProxmoxVMHardwareResult } from './models/ProxmoxVMHardwareResult';
export type { ProxmoxVMHardwareUpdateRequest } from './models/ProxmoxVMHardwareUpdateRequest';
export type { ProxmoxVMListResult } from './models/ProxmoxVMListResult';
export type { ProxmoxVMStartRequest } from './models/ProxmoxVMStartRequest';
export type { ProxmoxVMStartResult } from './models/ProxmoxVMStartResult';
export type { ProxmoxVMTemplateRequest } from './models/ProxmoxVMTemplateRequest';
export type { ProxmoxVMTemplateResult } from './models/ProxmoxVMTemplateResult';
export type { ProxmoxWorkload } from './models/ProxmoxWorkload';
export type { ProxmoxWorkloadInventoryResult } from './models/ProxmoxWorkloadInventoryResult';
export type { ProxyInstallRequest } from './models/ProxyInstallRequest';
export type { ProxyInstallResult } from './models/ProxyInstallResult';
export type { RolePermissionCount } from './models/RolePermissionCount';
export type { RolePermissionMappingDao } from './models/RolePermissionMappingDao';
export type { SoftDeleteRoleByIdRequest } from './models/SoftDeleteRoleByIdRequest';
export type { SoftDeleteRoleByIdResponse } from './models/SoftDeleteRoleByIdResponse';
export type { SoftDeleteUserByIdRequest } from './models/SoftDeleteUserByIdRequest';
export type { SoftDeleteUserByIdResponse } from './models/SoftDeleteUserByIdResponse';
export type { SshConnectionCloseResponse } from './models/SshConnectionCloseResponse';
export type { SshConnectionRequestDetails } from './models/SshConnectionRequestDetails';
export type { SshConnectionResponse } from './models/SshConnectionResponse';
export type { SshKeyListItem } from './models/SshKeyListItem';
export type { SSHOptions } from './models/SSHOptions';
export type { SshSessionSummary } from './models/SshSessionSummary';
export type { SystemdAppDeployRequest } from './models/SystemdAppDeployRequest';
export type { SystemdAppDeployResult } from './models/SystemdAppDeployResult';
export type { TokenRefreshReq } from './models/TokenRefreshReq';
export type { UpdateExternalApplicationRequest } from './models/UpdateExternalApplicationRequest';
export type { UpdateHostServerRequest } from './models/UpdateHostServerRequest';
export type { UpdateHostServerTypeBody } from './models/UpdateHostServerTypeBody';
export type { UpdatePlatformTypeBody } from './models/UpdatePlatformTypeBody';
export type { UpdateSshKeyHostMappingRequest } from './models/UpdateSshKeyHostMappingRequest';
export type { UpdateUserApplicationRequest } from './models/UpdateUserApplicationRequest';
export type { UpdateUserPasswordRequest } from './models/UpdateUserPasswordRequest';
export type { UpdateUserRoleMappingRequest } from './models/UpdateUserRoleMappingRequest';
export type { UpdateUserRoleMappingResponse } from './models/UpdateUserRoleMappingResponse';
export type { UserApplicationDao } from './models/UserApplicationDao';
export type { UserDao } from './models/UserDao';
export type { UserHostedDb } from './models/UserHostedDb';
export type { UserLoginRequest } from './models/UserLoginRequest';
export type { UserPasswordUpdateResponse } from './models/UserPasswordUpdateResponse';
export type { UserRoleDao } from './models/UserRoleDao';
export type { UserSecretEntry } from './models/UserSecretEntry';
export type { UUID } from './models/UUID';
export type { UUIDs } from './models/UUIDs';
export type { ValkeyInstallRequest } from './models/ValkeyInstallRequest';
export type { ValkeyInstallResult } from './models/ValkeyInstallResult';

export { Service } from './services/Service';
export { AuthenticationService } from './services/AuthenticationService';
export { CertificatesService } from './services/CertificatesService';
export { DeploymentService } from './services/DeploymentService';
export { ExternalApplicationsService } from './services/ExternalApplicationsService';
export { HostServersService } from './services/HostServersService';
export { NetworkPingService } from './services/NetworkPingService';
export { NetworkProbeService } from './services/NetworkProbeService';
export { PermissionsCrudService } from './services/PermissionsCrudService';
export { ProxmoxService } from './services/ProxmoxService';
export { RolesCrudService } from './services/RolesCrudService';
export { SecretsService } from './services/SecretsService';
export { SshService } from './services/SshService';
export { SshKeyHostMappingsService } from './services/SshKeyHostMappingsService';
export { SshKeysService } from './services/SshKeysService';
export { UserApplicationsService } from './services/UserApplicationsService';
export { UserCrudService } from './services/UserCrudService';
