server {
  listen 80;
  server_name dbbob.dev.justintrahan.com infractl.dev.justintrahan.com dbbob rockydev2 rockydev2.trahan.dev;

  return 301 https://$host:4443$request_uri;
}

server {
  listen 4443 ssl;
  http2 on;
  server_name dbbob.dev.justintrahan.com infractl.dev.justintrahan.com dbbob rockydev2 rockydev2.trahan.dev;

  ssl_certificate /etc/nginx/certs/cert.pem;
  ssl_certificate_key /etc/nginx/certs/privkey.pem;
  ssl_session_cache shared:SSL:1m;
  ssl_session_timeout 10m;
  ssl_ciphers PROFILE=SYSTEM;
  ssl_prefer_server_ciphers on;

  root /usr/share/nginx/html/dbbob;
  index index.html;

  location /api/ {
    proxy_pass http://localhost:8993/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}

